# Generated by Django 2.2.3 on 2019-09-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0009_auto_20190722_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='device_id',
            new_name='device_name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='number',
        ),
        migrations.AlterField(
            model_name='place',
            name='bronetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
