# Generated by Django 2.2.3 on 2019-09-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0011_reserves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='bronetime',
        ),
        migrations.AddField(
            model_name='place',
            name='bronetime_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='bronetime_start',
            field=models.DateTimeField(null=True),
        ),
    ]
